name: 'CI - Java'
on: pull_request
jobs:
  my-job:
    runs-on: ubuntu-latest
    needs: workflow
    steps:
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.MY_SECRET }}"
